version: "3.3"

services: 

  mongodb:
    image: mongo:bionic
    container_name: mongodb
    volumes: 
      - ./data:/data/db
    network_mode: "host"

  bluetooth:
    build: .
    container_name: bluetooth-discover
    privileged: true
    network_mode: "host"
    depends_on: 
      - mongodb