version: "3.9"

services: 

  db:
    image: mongo
    container_name: mongodb
    volumes: 
      - ./data:/data/db

  bluetooth:
    build: .
    container_name: bluetooth-discover
    privileged: true

