version: "3.3"

services: 

  db:
    image: mongo:bionic
    container_name: mongodb
    volumes: 
      - ./data:/data/db

  bluetooth:
    build: .
    container_name: bluetooth-discover
    privileged: true

